# Automação Excel - Notebook
Este notebook foi criado para análises e automações com arquivos Excel.

In [1]:
import pandas as pd
import numpy as np
import requests
import time

In [3]:
df = pd.read_csv('datasets/enderecos.csv', sep=';', encoding='latin1')
df.head()

,COLABORADOR,ENDERECO,TURNO
0,ADEMIR ALVES DA SILVA - CENTRAL,"RUA VICENTE DOS SANTOS, 90, BERNARDO MONTEIRO,...",CENTRAL
1,AGNALDO ALVES LOUBACK - CENTRAL,"RUA TUI, 127, ICAIVERA, CONTAGEM, MG",CENTRAL
2,AGNALDO FERREIRA CAMARGO - CENTRAL,"RUA CRISTA DE GALO, 510, ALTEROSA 2 SECAO, BET...",CENTRAL
3,ALBERTO SANGREMA CARVALHO - CENTRAL,"RUA MARANHÃO, 96, OURO NEGRO, IBIRITÉ, MG",CENTRAL
4,ALESSANDRO RODRIGUES DE SOUZA - CENTRAL,"RUA V, 8, VILA NOVA ESPERANÇA, CONTAGEM, MG",CENTRAL

In [5]:
def get_lat_long(endereco, api_key):
    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={endereco}&key={api_key}"
    response = requests.get(url)
    if response.status_code == 200:
        result = response.json()
        if result['status'] == 'OK':
            location = result['results'][0]['geometry']['location']
            return location['lat'], location['lng']
    return None, None

# Sua chave de API do Google
api_key = "AIzaSyCLqtViEn6cXb5ZkADoQdIHFyRMqjkeSTg"

# Lista para armazenar endereços não localizados
enderecos_nao_localizados = []

for idx, row in df.iterrows():
    endereco = row['ENDERECO']
    lat, lng = get_lat_long(endereco, api_key)
    df.at[idx, 'LATITUDE'] = lat
    df.at[idx, 'LONGITUDE'] = lng
    if lat is None or lng is None:
        enderecos_nao_localizados.append({'ENDERECO': endereco})
    time.sleep(0.2)  # Para evitar atingir o limite de requisições

# Salvar endereços não localizados em CSV
if enderecos_nao_localizados:
    df_nao_localizados = pd.DataFrame(enderecos_nao_localizados)
    arquivo_csv = 'enderecos_nao_localizados.csv'
    # Se já existir, faz append sem sobrescrever os antigos
    if os.path.exists(arquivo_csv):
        df_existente = pd.read_csv(arquivo_csv)
        df_nao_localizados = pd.concat([df_existente, df_nao_localizados]).drop_duplicates()
    df_nao_localizados.to_csv(arquivo_csv, index=False)

In [7]:
df.head()

,COLABORADOR,ENDERECO,TURNO,LATITUDE,LONGITUDE
0,ADEMIR ALVES DA SILVA - CENTRAL,"RUA VICENTE DOS SANTOS, 90, BERNARDO MONTEIRO,...",CENTRAL,-19.930526,-44.085594
1,AGNALDO ALVES LOUBACK - CENTRAL,"RUA TUI, 127, ICAIVERA, CONTAGEM, MG",CENTRAL,-19.857136,-44.147156
2,AGNALDO FERREIRA CAMARGO - CENTRAL,"RUA CRISTA DE GALO, 510, ALTEROSA 2 SECAO, BET...",CENTRAL,-19.932249,-44.165436
3,ALBERTO SANGREMA CARVALHO - CENTRAL,"RUA MARANHÃO, 96, OURO NEGRO, IBIRITÉ, MG",CENTRAL,-20.008619,-44.121936
4,ALESSANDRO RODRIGUES DE SOUZA - CENTRAL,"RUA V, 8, VILA NOVA ESPERANÇA, CONTAGEM, MG",CENTRAL,-19.829395,-44.150104

In [6]:
df.to_csv('enderecos_com_coordenadas.csv', index=False)