# Automação Excel - Notebook
Este notebook foi criado para análises e automações com arquivos Excel.

In [3]:
import pandas as pd
import numpy as np
import requests
import time

In [4]:
df = pd.read_csv('datasets/enderecos.csv', sep=';', encoding='utf-8')
df.head()

,COLABORADOR,ENDEREÇO,LATITUDE,LONGITUDE
0,AFONSO ELZEPER MOREIRA LEITE,"R. FLORIANÓPOLIS, 275 - BOM JESUS - MATOZINHOS",NaN,NaN
1,ANDERSON LUIZ,"BECO SÃO PEDRO, 25 - CABANA - BH",NaN,NaN
2,ANTONIO LUIZ DA SILVA,"AV. RODRIGUES ALVES, 322 - INDUSTRIAL AMERICAN...",NaN,NaN
3,BRUNO GUILHERME CARVALHO DE OLIVEIRA MARTINS,"R. BOLÍVIA, 321 - BOM JESUS - MATOZINHOS",NaN,NaN
4,CARLOS ROMILDO DE AZEVEDO,"RUA JOÃO TEIXEIRA, 40 JARDIM ALTEROSA - VESPAS...",NaN,NaN

In [5]:
# Função para obter latitude e longitude do endereço
def get_lat_long(endereco, api_key):
    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={endereco}&key={api_key}"
    response = requests.get(url)
    if response.status_code == 200:
        result = response.json()
        if result['status'] == 'OK':
            location = result['results'][0]['geometry']['location']
            return location['lat'], location['lng']
    return None, None

# Sua chave de API do Google
api_key = "AIzaSyCLqtViEn6cXb5ZkADoQdIHFyRMqjkeSTg"

# Preencher as colunas LATITUDE e LONGITUDE
for idx, row in df.iterrows():
    endereco = row['ENDEREÇO']
    lat, lng = get_lat_long(endereco, api_key)
    df.at[idx, 'LATITUDE'] = lat
    df.at[idx, 'LONGITUDE'] = lng
    time.sleep(0.2)  # Para evitar atingir o limite de requisições

In [6]:
df.head()

,COLABORADOR,ENDEREÇO,LATITUDE,LONGITUDE
0,AFONSO ELZEPER MOREIRA LEITE,"R. FLORIANÓPOLIS, 275 - BOM JESUS - MATOZINHOS",-19.567199,-44.065356
1,ANDERSON LUIZ,"BECO SÃO PEDRO, 25 - CABANA - BH",-19.950005,-44.000315
2,ANTONIO LUIZ DA SILVA,"AV. RODRIGUES ALVES, 322 - INDUSTRIAL AMERICAN...",-19.761445,-43.834727
3,BRUNO GUILHERME CARVALHO DE OLIVEIRA MARTINS,"R. BOLÍVIA, 321 - BOM JESUS - MATOZINHOS",-19.567109,-44.063932
4,CARLOS ROMILDO DE AZEVEDO,"RUA JOÃO TEIXEIRA, 40 JARDIM ALTEROSA - VESPAS...",-19.686292,-43.933411

In [7]:
df.to_csv('enderecos_com_coordenadas.csv', index=False)